### PR TITLE
Use prop-types instead of React.PropTypes

### PR DESCRIPTION
**Pull request by mozmorris**
See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

### CODE REVIEW

**Comment by mozmorris** [comment]
Hey @cezary, is this project still maintained? Would you be interested in transferring ownership if you don't intend to maintain it anymore?

**Comment by cezary** [comment]
Hi @mozmorris, definitely interested. See #44

**Comment by mozmorris** [comment]
Okay cool. It's late here and the weekend, but I'm interested for sure.

Can I catch up with you over the weekend?

**Comment by mozmorris** [comment]
And just to say, thanks for getting back to me. This package has been very useful to me and my team over the past year or so.

**Comment by cezary** [comment]
Thanks and my apologies for not maintaining it better. Feel free to get back to me whenever you have time and I'll happily transfer the github repo and npm package.

**Comment by mozmorris** [comment]
As I understand it, I'll need to delete my fork before you can transfer the repo. I'll do that now.

npm username is mozmorris

**Comment by cezary** [comment]
All done transferring the repo and the npm package over to you. Thanks and good luck!

**Comment by mozmorris** [comment]
Thanks again @cezary.

**Pull request closed without merging**
